AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation SES Providers
Resources:
  LambdaPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CFNSESProviderPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - lambda:InvokeFunction
            Resource:
              - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxio-cfn-ses-provider'
          - Effect: Allow
            Action:
              - route53:GetHostedZone
              - route53:ChangeResourceRecordSets
              - route53:ListResourceRecordSets
            Resource: '*'
          - Effect: Allow
            Action:
              - ses:VerifyDomainDkim
              - ses:DeleteIdentity
              - ses:ListIdentities
              - ses:VerifyDomainIdentity
              - ses:DescribeActiveReceiptRuleSet
              - ses:SetActiveReceiptRuleSet
              - ses:GetIdentityVerificationAttributes
              - ses:GetIdentityMailFromDomainAttributes
              - ses:GetIdentityNotificationAttributes
              - ses:SetIdentityNotificationTopic
              - ses:SetIdentityHeadersInNotificationsEnabled
              - ses:SetIdentityFeedbackForwardingEnabled
              - ses:SetIdentityMailFromDomain
              - ses:ListIdentityPolicies
              - ses:GetIdentityPolicies
              - ses:PutIdentityPolicy
              - ses:DeleteIdentityPolicy
            Resource: '*'
          - Effect: Allow
            Action:
              - logs:*
            Resource: arn:aws:logs:*:*:*
      Roles:
        - !Ref 'LambdaRole'

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com

  CFNSESProvider:
    Type: AWS::Lambda::Function
    DependsOn:
      - LambdaPolicy
    Properties:
      Description: CloudFormation SES provider implementation
      PackageType: Image
      Code:
        ImageUri: 463637877380.dkr.ecr.eu-central-1.amazonaws.com/xebia/cfn-ses-provider:0.8.3-66306b3-dirty
      FunctionName: binxio-cfn-ses-provider
      MemorySize: 128
      Role: !GetAtt 'LambdaRole.Arn'
      Timeout: 30
