AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation SES Providers
Parameters:
  LambdaS3Bucket:
    Type: String
    Default: ''
  CFNSESProviderZipFileName:
    Type: String
    Default: ''
Conditions:
  UsePublicBucket: !Equals
    - !Ref 'LambdaS3Bucket'
    - ''
  UsePublicLambda: !Equals
    - !Ref 'CFNSESProviderZipFileName'
    - ''
Resources:
  LambdaPolicy:
    Type: AWS::IAM::Policy
    DependsOn:
      - LambdaRole
    Properties:
      PolicyName: CFNSESProviderPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - route53:GetHostedZone
              - route53:ChangeResourceRecordSets
              - route53:ListResourceRecordSets
            Resource: '*'
          - Effect: Allow
            Action:
              - ses:VerifyDomainDkim
              - ses:DeleteIdentity
              - ses:ListIdentities
              - ses:VerifyDomainIdentity
            Resource: '*'
          - Effect: Allow
            Action:
              - logs:*
            Resource: arn:aws:logs:*:*:*
      Roles:
        - !Ref 'LambdaRole'
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
  CFNSESProvider:
    Type: AWS::Lambda::Function
    DependsOn:
      - LambdaRole
      - LambdaPolicy
    Properties:
      Description: CloudFormation SES provider implementation
      Code:
        S3Bucket: !If
          - UsePublicBucket
          - !Sub 'binxio-public-${AWS::Region}'
          - !Ref 'LambdaS3Bucket'
        S3Key: !If
          - UsePublicLambda
          - lambdas/cfn-ses-provider-0.6.3.zip
          - !Ref 'CFNSESProviderZipFileName'
      FunctionName: binxio-cfn-ses-provider
      Handler: ses.handler
      MemorySize: 128
      Role: !GetAtt 'LambdaRole.Arn'
      Runtime: python3.6
      Timeout: 30
