AWSTemplateFormatVersion: '2010-09-09'
Description: Demo SES provider
Parameters:
  DomainName:
    Type: String
    Default: 'mark.binx.dev'
  HostedZoneId:
    Type: 'String'
    Default: /hostedzone/Z0371259XDZLRTIQJZIY

Resources:
  DomainIdentity:
    Type: Custom::DomainIdentity
    Properties:
      Domain: !Ref 'DomainName'
      Region: !Ref 'AWS::Region'
      RecordSetDefaults:
        TTL: 60
        Weight: 1
        SetIdentifier: !Ref 'AWS::Region'
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxio-cfn-ses-provider'

  VerifiedIdentity:
    Type: Custom::VerifiedIdentity
    DependsOn:
      - DkimRecords
      - VerificationRecords
    Properties:
      Identity: !GetAtt DomainIdentity.Domain
      Region: !GetAtt DomainIdentity.Region
      Dummy: true
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxio-cfn-ses-provider'

  VerificationRecords:
    Type: AWS::Route53::RecordSetGroup
    Properties:
        Comment: !Sub 'SES identity for ${DomainName}'
        HostedZoneId: !Ref 'HostedZoneId'
        RecordSets: !GetAtt 'DomainIdentity.RecordSets'

  DkimTokens:
    Type: Custom::DkimTokens
    Properties:
      Domain: !GetAtt 'DomainIdentity.Domain'
      Region: !GetAtt 'DomainIdentity.Region'
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxio-cfn-ses-provider'

  DkimRecords:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      Comment: !Sub 'DKIM records for ${DomainName}'
      HostedZoneId: !Ref 'HostedZoneId'
      RecordSets: !GetAtt 'DkimTokens.RecordSets'

  SnsTopic:
    Type: AWS::SNS::Topic

  IdentityNotifications:
    Type: Custom::IdentityNotifications
    Properties:
      Identity: !GetAtt VerifiedIdentity.Identity
      Region: !GetAtt VerifiedIdentity.Region
      BounceTopic: !Ref SnsTopic
      ComplaintTopic: !Ref  SnsTopic
      HeadersInBounceNotificationsEnabled: true
      HeadersInComplaintNotificationsEnabled: true
      ForwardingEnabled: false
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxio-cfn-ses-provider'

