AWSTemplateFormatVersion: '2010-09-09'
Description: Demo SES provider
Parameters:
  ExternalDomainName:
    Type: String
    Default: ses.cfn.internal
Resources:
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref 'ExternalDomainName'
  DKIM:
    Type: Custom::Domain
    DependsOn: HostedZone
    Properties:
      HostedZoneId: !Ref 'HostedZone'
      DKIM: true
      ServiceToken: !Join
        - ':'
        - - arn:aws:lambda
          - !Ref 'AWS::Region'
          - !Ref 'AWS::AccountId'
          - function:binxio-cfn-ses-provider
